const BROWN_DAIRY_CREAM = '#E3C698';
const BROWN_HEMP = '#917769';
const BROWN_HOT_TODDY = '#B27F3C';
const BROWN_PALE_BROWN = '#8E6D46';
const BROWN_COPPER_RUST = '#984F47';
const RED_GRENADIER = '#C05038';
const RED_GRENADIER_LIGHT = '#db9383';
const VIOLET_COMET = '#636777';
const BROWN_TUSCANY = '#B16642';
const GREY_HEAVY_METAL = '#393D34';
const YELLOW_SAHARA = '#BF9C2A';
const YELLOW_SAHARA_LIGHT = '#EFE1B5';
const YELLOW_SAHARA_DARK = '#CDA72D';

export const BASE_BACKGROUND = BROWN_DAIRY_CREAM;

export const PRIMARY_BACKGROUND = RED_GRENADIER;
export const PRIMARY_FOREGROUND = GREY_HEAVY_METAL;

export const SECONDARY_BACKGROUND = RED_GRENADIER_LIGHT;
export const SECONDARY_FOREGROUND = BROWN_COPPER_RUST;


export const FACT_COLOR = VIOLET_COMET;
export const FACT_BACKGROUND_COLOR = YELLOW_SAHARA_LIGHT;
export const FACT_BORDER_COLOR = YELLOW_SAHARA_DARK;

export const EVENT_QUOTE_USER_COLOR = BROWN_TUSCANY;

export const COLOR_TIMELINE_LINE = YELLOW_SAHARA_LIGHT;
export const COLOR_TIMELINE_CIRCLE = YELLOW_SAHARA_DARK;
export const COLOR_TIMELINE_FILLED = RED_GRENADIER;

// export const COLOR_TIMELINE_LINE = "#c2c1c0";
// export const COLOR_TIMELINE_CIRCLE = "#c2c1c0";

export const COLOR_THEME_PRIMARY = "#40BABF";
export const COLOR_THEME_SECONDARY = "#BF4540";


export const COLOR_BUTTON_BACKGROUND = COLOR_THEME_PRIMARY;
export const COLOR_BUTTON_TEXT = "#FFFFFF";

export const COLOR_LOVE_HEART = RED_GRENADIER;