export const FETCH_USER_REQUEST = "user:FETCH_USER_REQUEST";
export const FETCH_USER_FAILURE = "user:FETCH_USER_FAILURE";
export const FETCH_USER_SUCCESS = "user:FETCH_USER_SUCCESS";
export const UPDATE_CURRENT_USERNAME = "user:UPDATE_CURRENT_USERNAME";
