export const NAVIGATE_T0_SPLASH_SCREEN = "NAVIGATION.NAVIGATE_T0_LOGIN_SCREEN";
export const NAVIGATE_T0_LOGIN_SCREEN = "NAVIGATION.NAVIGATE_T0_LOGIN_SCREEN";
export const NAVIGATE_T0_APP_SCREEN = "NAVIGATION.NAVIGATE_T0_APP_SCREEN";

export const NAVIGATE_T0_VIRO_VIEW = "NAVIGATION.NAVIGATE_T0_VIRO_VIEW";
export const NAVIGATE_T0_LIKES_VIEW = "NAVIGATION.NAVIGATE_T0_LIKES_VIEW";
export const NAVIGATE_T0_ACCOUNT_VIEW = "NAVIGATION.NAVIGATE_T0_ACCOUNT_VIEW";
export const NAVIGATE_T0_CARD_VIEW = "NAVIGATION.NAVIGATE_TO_CARD_VIEW";
export const NAVIGATE_T0_CARD_SELECTED_VIEW = "NAVIGATION.NAVIGATE_TO_CARD_SELECTED_VIEW";
export const NAVIGATE_T0_CARD_PREVIEW_VIEW = "NAVIGATION.NAVIGATE_TO_CARD_PREVIEW_VIEW";