export const NAVIGATE_TO_SINGLE_HISTORIC_EVENT_MAIN = "navigate:NAVIGATE_TO_SINGLE_HISTORIC_EVENT_MAIN";
export const NAVIGATE_TO_SINGLE_HISTORIC_EVENT_DETAIL = "navigate:NAVIGATE_TO_SINGLE_HISTORIC_EVENT_DETAIL";

export const NAVIGATE_TO_TIMELINE_HISTORIC_EVENTS = "navigate:NAVIGATE_TO_TIMELINE_HISTORIC_EVENTS";
export const NAVIGATE_TO_LIKED_EVENTS = "navigate:NAVIGATE_TO_LIKED_EVENTS";